
ALTER TABLE `dev_db`.`tb_user` 
CHANGE COLUMN `USER_ID` `USER_ID` INT(11) NOT NULL AUTO_INCREMENT COMMENT 'userId' ,
ADD UNIQUE INDEX `USER_ID_UNIQUE` (`USER_ID` ASC);


CREATE TABLE `tb_user` (
  `USER_ID` int(11) NOT NULL AUTO_INCREMENT COMMENT 'userId',
  `USER_NM` varchar(45) DEFAULT NULL COMMENT 'user name',
  `USER_ADDR` varchar(120) DEFAULT NULL COMMENT 'address\n',
  `USER_EMAIL` varchar(80) DEFAULT NULL COMMENT 'email',
  `USER_TYPE` int(1) DEFAULT '1' COMMENT '1:man 2:woman',
  PRIMARY KEY (`USER_ID`),
  UNIQUE KEY `USER_ID_UNIQUE` (`USER_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;


-- 
CREATE TABLE `tb_category` (
  `CA_SEQ` INT NOT NULL AUTO_INCREMENT,
  `NAME` VARCHAR(120) NOT NULL,
  `PARENT_SEQ` INT NOT NULL DEFAULT 0,
  PRIMARY KEY (`CA_SEQ`),
  UNIQUE INDEX `CA_SEQ_UNIQUE` (`CA_SEQ` ASC))
COMMENT = '카테고리 관리';


